lamp = input("Enter a name for the lamp: ")
number = input("Enter the number of wish: ")
wish = input("Enter the wish: ")
ginie = input("Enter the name for ginie: ")
emotion = input("Enter the emotion that the boy feels: ")
print("In a quiet village, a boy found a" +lamp+".") 
print("When he rubbed it, a genie appeared, offering"+number+"wish.")
print("The boy wished for"+wish+".")
print("Every night, the "+genie+" spun tales of adventure and wonder, filling the boy’s life with"+emotion+" and the village with enchantment.")
